name: Build and Deploy Jekyll site
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      # Add debugging step to show contents of _config.yml
      - name: Debug Config
        run: |
          echo "Contents of _config.yml:"
          cat _config.yml
          echo "Current directory contents:"
          ls -la

      # Ensure baseurl and url are set correctly for build
      - name: Build Site
        run: |
          SITE_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          echo "Building site with url: $SITE_URL"
          JEKYLL_ENV=production bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production

      # Debug built site contents
      - name: Debug Built Site
        run: |
          echo "Contents of _site directory:"
          ls -la _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # Add this to keep .nojekyll file
          enable_jekyll: false
          # Add this to ensure we keep the .nojekyll file
          keep_files: false
          # Add commit message for clarity
          commit_message: "Deploy Jekyll site via GitHub Actions"